---
title: "networkpresentdchistupdated"
author: "George Oberle"
date: "October 27, 2015"
output: html_document
---

```{r}
#Load tools
library (sp)
library (rgdal)
library (rgeos)
library (maptools)
library (ggmap)
library (ggplot2)
library (mullenMisc)
library (magrittr)
library (stringr)
library (dplyr)
library (RColorBrewer)
library (igraph)
library (readr)
```


#Load the data of the all the societies so far
```{r}
netsoc = read.csv("data/networksocieties.csv")
```


Full Network. 
```{r}
societies_edges <- read_csv("Data/societies-edge-attr.csv")
societies_nodes <- read_csv("Data/societies-node-attr.csv")
```

```{r}
societies_g <- graph_from_data_frame(societies_edges, directed = FALSE, societies_nodes)
```

uncomment to use comment to set
```{r}
#png(filename = "societies-network.png", width = 2400, height = 1600, res = 300, pointsize = 10)
set.seed(845)
par(mar = c(1, 1, 1, 1))
l <- layout.fruchterman.reingold(societies_g, weights = E(societies_g))
plot(societies_g, 
     layout = l,
     edge.width = E(societies_g)$weight * 0.4,
     vertex.size = 15,
     vertex.label.color = "black",
     vertex.label.cex = 3,
     edge.color="light blue")
title("Early American Societies", font.main= 2) 

```

```{r}
#png(filename = "societies-network.png", width = 2400, height = 1600, res = 300, pointsize = 10)
set.seed(845)
par(mar = c(1, 1, 1, 1))
l <- layout.star(societies_g)
plot(societies_g, 
     layout = l,
     edge.width = E(societies_g)$weight * 0.4,
     vertex.size = 15,
     vertex.label.color = "black",
     vertex.label.cex = 3,
     edge.color="dark blue")
title("Early American Societies", font.main= 2) 


```


uncomment to use comment to set
```{r}
#dev.off()
```

